name: Tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r music_generator/requirements.txt

      - name: Add src to PYTHONPATH
        run: echo "PYTHONPATH=$PYTHONPATH:$(pwd)/music_generator/src" >> $GITHUB_ENV

      - name: Run tests with coverage
        run: |
          pytest --cov=. --cov-report=xml

      - name: Run pylint
        run: |
          pylint $(git ls-files '*.py') || true

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage.xml



